server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-wwo3hakti0001ao.rwlb.rds.aliyuncs.com:3306/magicnote
    Username: testuser
    password: Java-123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      static-path-pattern: "/resources/**"

  security:
    user:
      name: admin
      password: admin

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
# 生成openssl rand -hex 64
jwt:
  secret: f2522288621c04bf9b182a129a19853080112a2b805973060684fb6484cb537c750596109d844a62f683a187d54c3cb5d54e8301530de30a43fb870b5dbf27f7

tess4j:
  datapath: D:/Dataset/tessdata


# minio 文件存储配置信息
minio:
  endpoint: http://192.168.80.1:9000
  accesskey: minioadmin
  secretKey: minioadmin