server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/magicnote
#    Username: root
#    password: 159463728
    url: jdbc:mysql://121.41.176.221:3306/magicnote
    Username: root
    password: Aa159463728=
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      static-path-pattern: "/resources/**"

  security:
    user:
      name: admin
      password: admin

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
# 生成openssl rand -hex 64
jwt:
  secret: f2522288621c04bf9b182a129a19853080112a2b805973060684fb6484cb537c750596109d844a62f683a187d54c3cb5d54e8301530de30a43fb870b5dbf27f7
  header-name: "Authorization"  # jwt token包含在header的哪个字段中
  ttl: 14400000 # token的过期时间, 4个小时

tess4j:
  datapath: D:/Dataset/tessdata


# minio 文件存储配置信息
minio:
  endpoint: http://118.178.241.148:9000
  accesskey: minioadmin
  secretKey: minioadmin


chatgpt:
  token: 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
  proxy-host: 127.0.0.1 #需要代理时必填
  proxy-port: 7890 #需要代理时必填
  #  model: text-davinci-003 #可选
  chat-model: gpt-3.5-turbo #可选
  #  retries: 10 #可选，默认为5
  session-expiration-time: 30 #可选，不填则会话永不过期
  # base-url: https://api.openai.com/
